[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.0"
shuttle-axum = { version = "0.1.0" }
shuttle-runtime = { version = "0.1.0" }
tokio = { version = "1.22.0", features = ["rt", "rt-multi-thread", "sync"] }
