[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.148", features = ["derive"] }
shuttle-aws-rds = { version = "0.11.0", features = ["postgres"] }
shuttle-service = { version = "0.11.0", features = ["web-tide"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres"] }
tide = "0.16.0"
